### ISSUE TITLE
Remove brp-40-rootfs after rpmlint2 is released

### ISSUE THREAD

**Issue by marxin** [openSUSE/brp-check-suse#25]
@scarabeusiv 
The script is redundant to `rpmlint` check named `linked-against-opt-library`.

**Comment by coolo** [comment]
rpmlint is at 1.11 in Tumbleweed

**Comment by scarabeusiv** [comment]
@coolo we are taking ages to implement it due to resources available: https://github.com/rpm-software-management/rpmlint/milestone/1
