### ISSUE TITLE
desktop categories issues

### ISSUE THREAD

**Issue by krop** [openSUSE/brp-check-suse#26]
https://github.com/openSUSE/brp-check-suse/pull/18 entered openSUSE Factory a couple days ago.
It causes quite some build issues.

example 1:
 
> [  148s] + /usr/lib/rpm/suse_update_desktop_file.sh -r spyder Qt Science ComputerScience Development IDE
> [  148s] WARNING: Category "ComputerScience" is unknown \!

According to https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#Science, `ComputerScience` can be a subcategory of either `Education` or `Science`

example 2: 
Fixing mayavi.desktop to have
`Categories=GNOME;Education;DataVisualization;X-Science,X-DataVisualization;`
now makes the build fail for leap with an unknown categories error

example 3:

> [  128s] ERROR: No sufficient Category definition "Qt;KDE;Education;X-KDE-Edu-Misc;X-KDE-Edu-Teaching;" in /home/abuild/rpmbuild/BUILDROOT/ktouch-19.08.0-1.2.i386//usr/share/applications/org.kde.ktouch.desktop 

The categories are valid. `X-KDE-Edu-Teaching` is the only one accepted and `X-KDE-Edu-Misc` is compliant with the XDG spec.

I'm looking at the other issues. `Teaching` now being rejected is the cause of multiple failures.

**Comment by krop** [comment]
cc @coolo

**Comment by bnavigator** [comment]
Teaching should be accepted with the fix in #27, but I do not understand yet why  Science;ComputerScience should fail. The warning message also does not come from brp-30-desktop but from the update desktop macro.

**Comment by bnavigator** [comment]
I have submitted a (package update)[https://build.opensuse.org/request/show/72993] to update-desktop-files to fix the `ComputerScience` warning.

Is it /really/ to OpenSUSE spec that "Education;X-KDE-Teaching" is a sufficient category definition? I would read the category listing in the wiki differently.

**Comment by bnavigator** [comment]
#27 (finally) made it into Factory. Do you still have issues with `Teaching` and `X-KDE-Edu-Teaching`?

**Comment by coolo** [comment]
the check is gone - see #14
