### ISSUE TITLE
Science categories

### ISSUE THREAD

**Issue by rdmitry** [openSUSE/brp-check-suse#4]
According to [freedesktop.org](http://standards.freedesktop.org/menu-spec/latest/apas02.html) categories like Science/Physics are allowed. But brp-30-desktop returns "ERROR: No sufficient Category definition"

**Comment by alexey-lcard** [comment]
Same problem with DataVisualization, ComputerScience, Geology, Robotics and many others additional categories for Science or Education (specified in https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#SUSE_specific_categories)....  but no problem with Science/Math

**Comment by arunpersaud** [comment]
ran into the same issue when updating gwyddion on OBS. It has categories in its desktop file that should be fine, e.g. science physics, but only science math worked, also tried datavisualization and some others (chemistry worked too btw).

**Comment by lnussel** [comment]
for rudi I guess

**Comment by coogor** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1074711

**Comment by lnussel** [comment]
If neither @bugfinder nor @nadvornik care I'd propose to just drop the check in brp-check-suse

**Comment by zaitor** [comment]
@adrianschroeter that is fine, but could we get the check up to date on what is and what is not ok ref https://specifications.freedesktop.org/menu-spec/latest/apas02.html

Every time I get a buildfail due to "ERROR: No sufficient Category definition" I get the urge to throw my monitor across the room.

**Comment by lnussel** [comment]
so no progress here for years. time to get rid of brp-desktop I guess

**Comment by bnavigator** [comment]
Still no progress...

**Comment by bnavigator** [comment]
Ok I tried to fix Science and education in #18. Someone else can do the rest. Maybe there should be a single definition which feeds the guidelines, the %suse_update_desktop_file macro and the brb-desktop check

**Comment by bnavigator** [comment]
Oh and #13 tried to fix it in a more generic way, but was discarded for unclear reasons.

Meanwhile I am told in https://bugzilla.opensuse.org/show_bug.cgi?id=1074711 that trying to help with a PR is futile. Open source at it's best.

**Comment by coolo** [comment]
See #14
