### ISSUE TITLE
brp-25-symlink fails with symlinks pointing to file in a package with postfixes

### ISSUE THREAD

**Issue by hellcp** [openSUSE/brp-check-suse#42]
`RemovePathPostfixes` allows us to do some neat things with placing multiple files in the same place in rpms, but brp doesn't know that symlinks pointing to that actually end up existing in the package, because they don't exist in the buildroot

**Comment by coolo** [comment]
You will have to provide more infos here, I have no idea what you're talking about

**Comment by hellcp** [comment]
https://build.opensuse.org/package/show/home:hellcp:branches:Base:System/distribution-logos-openSUSE this should pass

**Comment by coolo** [comment]
Thanks for the pointer. Not sure I can handle that from brp script

**Comment by coolo** [comment]
And even if, the solution for that will only end up in Tumbleweed. You seem to target Leap as well.

So better use this for your package:
```
 %install
+export NO_BRP_STALE_LINK_ERROR=yes
 mkdir -p %{buildroot}%{_datadir}/pixmaps/distribution-logos

**Comment by hellcp** [comment]
Thanks, that helps!

**Comment by coolo** [comment]
The alternative is having e.g. Tumbleweed icon without suffix - then you don't need the hack.

But I can't support this feature in general, the Buildroot looks greatly different than the final files, so checking in there is even more guesswork than it already is.
