### ISSUE TITLE
brp-30-desktop is inconsistent with wiki

### ISSUE THREAD

**Issue by heinervdm** [openSUSE/brp-check-suse#5]
brp-30-desktop fails on categories=Education;Science; with the error message:
 ERROR: No sufficient Category definition:

But according to https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories this category is allowed. As I think the check should check what's agreed on and not change the allowed categories to be determined by the check, this is a bug in the check. Also there are several comments below the corresponding commit complaining about similar issues: https://github.com/openSUSE/brp-check-suse/commit/031533d7bb03c467fa8c8c8ec32b62b5bc9f405b

**Comment by lnussel** [comment]
@stanislav-brabec, @bugfinder?

**Comment by stanislav-brabec** [comment]
This is correct behavior. Education is a main category, Science is now main category as well (it was secondary in past, and it was required to be used together with Education. Now Science is allowed as a main category without Education).

You defined a desktop file, which has two main categories defined (it is possible), but no additional category defined. You have to define one secondary category for each main category (in case of Education;Science;, both could have the same secondary category).

You have to specify _which science_ is it:
http://standards.freedesktop.org/menu-spec/latest/apas02.html

**Comment by stanislav-brabec** [comment]
https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories needs update (or removal in favor of Freedesktop spec). It refers to the old version of desktop specification.

This issue is a consequence of [Bug 20186 - menu-spec Categories: clash of Science and Education => new main Category ](https://bugs.freedesktop.org/show_bug.cgi?id=20186)

**Comment by stanislav-brabec** [comment]
I just did a large edit of https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories

Now the page should 100% match with the Freedesktop Menu Spec (Fri Apr 4 2014), but there are still possible differences to brp checks. If some of them will be found, they can be reported as bugs.

I propose to close this report. It was a documentation fault, not a code fault.
